[build]
  command = "npm run build"
  publish = ".compiiile/dist"

[build.environment]
  NODE_VERSION = "24"

# Configuration pour les redirections (optionnel)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers de sécurité (optionnel mais recommandé)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuration pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
